# Import Libraries

In [36]:
# Import the Pandas library and alias it as "pd" for data calculations
import pandas as pd

# Import the pathlib function from the Path package for working with file paths
from pathlib import Path

# Import the csv package for reading and writing CSV files
import csv

# Import the 'datetime' class from the 'datetime' module for working with dates and times
from datetime import datetime

# Ignore warnings to prevent them from being displayed
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor

import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.statespace.sarimax import SARIMAX
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.preprocessing import MinMaxScaler

# Data Cleaning

In [2]:
#Read The 'user input' csvs

ui1 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Income Sources By Age and Tax.csv"))
ui2 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Household Liabilities.csv"))
ui4 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Canada_per_capita_income.csv"))
ui5 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\canada_cpi.csv"))
ui6 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\ca_real_estate.csv"))
ui7 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Average  OSAP Debt.csv"))
ui8a = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\World Happiness Reports\2015.csv"))
ui8b = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\World Happiness Reports\2016.csv"))
ui8c = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\World Happiness Reports\2017.csv"))
ui8d = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\World Happiness Reports\2018.csv"))
ui8e = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\World Happiness Reports\2019.csv"))
ui8f = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\World Happiness Reports\2020.csv"))
ui8g = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\World Happiness Reports\2021.csv"))
ui8h = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\World Happiness Reports\2022.csv"))
ui9a = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Household Wealth\All Household Wealth Stats.csv"))
ui9b = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Household Wealth\Highest Income Wealth Stats.csv"))
ui9c = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Household Wealth\Household Wealth Above 65.csv"))
ui9d = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Household Wealth\Household Wealth Below 64.csv"))
ui9e = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Household Wealth\Low Income Household Wealth Stats.csv"))
ui9f = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Household Wealth\Median Income Wealth.csv"))
ui9g = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Household Wealth\Under 35s Household Wealth.csv"))
ui9h = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Household Wealth\Under 44 Household Wealth.csv"))
ui9i = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Household Wealth\Under 54 Household Wealth.csv"))
ui10a = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Census\2001 Census.csv"))
ui10b = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Census\2006 Census.csv"))
ui10c = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Census\2011 Census.csv"))
ui10d = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Census\2016 Census.csv"))
ui10e = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Census\2021 Census.csv"))
ui11 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\UserInput\Age Classification Map.csv"))

In [3]:
#Read in the 'Canada' csvs
CA1 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Vital Food Costs.csv"))
CA2a = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\USDCAD Monthly Price.csv"))
CA2b = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\USDCAD Daily Price.csv"))
CA3 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\travel insurance.csv"))
CA4 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Share Of New Mortgage Holders With 660 Credit Score Or Below.csv"))
CA5 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Monthly retail trade sales by province and territory.csv"))
CA6 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Interest Rates.csv"))
CA7 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Housing Market Indicators Report.csv"))
CA8 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Government of Canada Spend By Industry.csv"))
CA9 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Farm Income Stats.csv"))
CA10 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Distributions of household economic accounts, income, consumption and saving.csv"))
CA11 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Canada_per_capita_income.csv"))
CA12 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\canada_gas_prices.csv"))
CA13 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\canada_cpi.csv"))
CA14 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Canada Historical GDP.csv"))
CA15 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Canada DeathData.csv"))
CA17 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Average Scheduled Monthly Payments On Mortgages.csv"))
CA18 = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Annual_Payday_Loan_Data.csv"))
CA19a = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Wages\Average Weekly Wage.csv"))
CA19b = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Wages\Hourly Wage Average By Industry.csv"))
CA19c = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Wages\Average Weekly Wage.csv"))
CA19d = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Wages\Household Wealth Below 64.csv"))
CA20a = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Income Groups\Canada Employment Income.csv"))
CA20b = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Income Groups\Canada Investment Income.csv"))
CA20c = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Income Groups\Canada Self Employment Income.csv"))
CA20d = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Income Groups\Canada Social Assistance Income.csv"))
CA20e = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Income Groups\Canada Total Income.csv"))
CA21a = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Import Export\Canadian Export Industries (millions of CAD).csv"))
CA21b = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Import Export\Canadian Import Industries (millions of CAD).csv"))
CA21c = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Import Export\Total Exports (millions of CAD).csv"))
CA21d = pd.read_csv(Path(r"C:\Users\Oluwa\GITHUB\Bootcamp\ASSIGNMENTS\Group-3-Project\Resources\Canada\Import Export\Total Imports (millions of CAD).csv"))

In [4]:
#Clean User Input Data

#Clean the first CSV
ui1 = ui1.set_index('REF_DATE')
ui1 = ui1[~ui1['Gender (3a)'].isin(['Women+', 'Men+'])]
ui1 = ui1.drop(columns=['Gender (3a)','Income statistics (16):Total - Population aged 15 years and over with an amount - 25% sample data (2015)[12]', 'Income statistics (16):Percentage with an amount (%) - 25% sample data (2015)[13]', 'Income statistics (16):Total - Population aged 15 years and over with an amount - 100% data (2015)[9]', 'Income statistics (16):Percentage with an amount (%) - 100% data (2015)[10]','Income statistics (16):Percentage with an amount (%) - 25% sample data (2020)[5]','Income statistics (16):Total - Population aged 15 years and over with an amount - 25% sample data (2020)[4]','Income statistics (16):Percentage with an amount (%) - 100% data (2020)[2]','Income statistics (16):Total - Population aged 15 years and over with an amount - 100% data (2020)[1]','DGUID','Coordinate', 'Symbol', 'Symbol.1', 'Symbol.2', 'Symbol.3', 'Symbol.4', 'Symbol.5', 'Symbol.6', 'Symbol.7', 'Symbol.8', 'Symbol.9', 'Symbol.10', 'Symbol.11', 'Symbol.12', 'Symbol.13', 'Symbol.14', 'Symbol.15'])
ui1 = ui1.rename(columns={
    'GEO': 'Location',
    'Age (9)': 'Age Group',
    'Income sources and taxes (32)': 'Income Source Types',
    'Income statistics (16):Median amount ($) (2020)[3]': '1 Year Median',
    'Income statistics (16):Average amount ($) (2020)[6]': '1 Year Average',
    'Income statistics (16):Aggregate amount ($\'000) (2020)[7]': '1 Year Aggregate',
    'Income statistics (16):As a share of total income (%) (2020)[8]': 'Percent of Total Income (1 Year)',
    'Income statistics (16):Median amount ($) (2015)[11]': '5 Year Median',
    'Income statistics (16):Average amount ($) (2015)[14]': '5 Year Average',
    'Income statistics (16):Aggregate amount ($\'000) (2015)[15]': '5 Year Aggregate',
    'Income statistics (16):As a share of total income (%) (2015)[16]': 'Percent of Total Income (5 Year)'
})
ui1['Location'] = ui1['Location'].str.split('(').str[0]
income_2021_bylocation_byage_byincomesource = ui1.groupby(['Location', 'Age Group', 'Income Source Types']).mean()


#Clean The Second
ui2.columns = ui2.iloc[0]
ui2 = ui2.iloc[1:]
ui2 = ui2.loc[:, ~ui2.iloc[0].str.contains('Symbol')]
ui2 = ui2.dropna()
ui2 = ui2.transpose()
ui2 = ui2.reset_index()
ui2.columns = ui2.iloc[0]
ui2 = ui2.iloc[1:]
ui2 = ui2.set_index('Period')
ui2 = ui2.drop(columns= ['Geography','Of which: off balance-sheet NHA-MBS 9 10 12', 'Non-residential mortgages 14','Of which: real estate secured lending 14','Residential mortgages 14', 'Chartered banks 10 14','Non-banks 10 14','Chartered banks 13 14','Non-banks 13 14','Home equity lines of credit 14','Chartered banks 14','Non-banks 14 15'])
household_liability_indexed_by_date = ui2.rename(columns={
    'Non-mortgage loans': 'Total Non-Mortgage',
    'Chartered banks 1': 'Non-Mortgage Chartered Banks',
    'Personal loans 1 2': 'Non-Mortgage Personal Loans',
    'Of which: Auto loans 1 2': 'Personal Loans for Automobiles',
    'Credit cards 1 2': 'Credit Card Liabilities',
    'Lines of credit 1 2 4' : 'Non-Mortgage Lines of credit',
    'Lines of credit, of which: excluding home equity lines of credit 1 2': 'Non-Mortgage Lines Of Credit (Excluding Home Equity LsOc)',
    'Other personal loans 1 2': 'Other personal loans',
    'Unincorporated business 1 2': 'Unincorporated Business',
    'Non-banks 1' : 'Non-bank Non-Mortgage loans',
    'Government 1 5' : 'Government Non-Mortgage Loans',
    'Non-bank financial corporations 1 5' : 'Non-bank Financial Institutions Non-Mortgage Loans',
    'Credit unions and caisse populaires 1 5' : 'Non-Mortgage Loans From Credit unions and caisse populaires',
    'Trust companies and mortgage loan companies 1 5' : 'Non-Mortgage Loans From Trust and Mortgage Loan Companies',
    'Financial vehicle corporations engaged in securitization 1 6' : 'Non-Mortgage Securities From Securitization Corporations',
    'Other financial corporations n.e.i. 1 7' : 'Other Non-Mortgage financial corporations',
    'Other lenders n.e.i. 1 8' : 'Other Non-Mortgage Lenders',
    'Mortgage Loans' : 'Total Mortgage',
    'Residential mortgages 9' : 'Residential Mortgages Total',
    'Chartered banks 9 10' : 'Residential Mortgages From Chartered Banks',
    'Non-banks 9 10' : 'Residential Mortgages From Non-Banks',
    'Government 9 10' : 'Residential Mortgages from Government Loans',
    'Non-bank financial corporations 9 10 11' : 'Residential Mortgages from Non-Bank Financial Institutions',
    'Credit unions and caisse populaires 9 10' : 'Residential Mortgages from Credit unions and caisse populaires',
    'Trust companies and mortgage loan companies 9 10' : 'Residential Mortgages From Trust and Mortgage Loan Companies',
    'Financial vehicle corporations engaged in securitization 6 9 10' : 'Residential Mortgages From Securitization Corporations',
    'Other financial corporations n.e.i. 7 9 10' : 'Residential Mortgages From Other Financial Corporations',
    'Other lenders n.e.i. 8 9 10' : 'Residential Mortgages From Other Lenders',
    'Non-residential mortgages 9' : 'Non-Residential Mortgages Total',
    'Chartered banks 9 13' : 'Non-Residential Mortgages From Chartered Banks',
    'Non-banks 9 13' : 'Non-Residential Mortgages From Non-Banks',
    'Government 9 13' : 'Non-Residential Mortgages from Government Loans',
    'Non-bank financial corporations 9 13' : 'Non-Residential Mortgages from Non-Bank Financial Institutions',
    'Credit unions and caisse populaires 9 13' : 'Non-Residential Mortgages from Credit unions and caisse populaires',
    'Trust companies and mortgage loan companies 9 13' : 'Non-Residential Mortgages From Trust and Mortgage Loan Companies',
    'Financial vehicle corporations engaged in securitization 6 9 13' : 'Non-Residential Mortgages From Securitization Corporations',
    'Other financial corporations n.e.i. 7 9 13' : 'Non-Residential Mortgages From Other Financial Corporations',
    'Other lenders n.e.i. 8 9 13' : 'Non-Residential Mortgages From Other Lenders',
    'Total credit liabilities of households' : 'Total Canada Credit Liability',
})

#Clean The Third
Income_Per_Capita_indexed_by_date = ui4.set_index('year')

#Clean The Fourth
Canada_CPI_Indexed_By_Date = ui5.set_index('Year')

#Clean The Fifth
ui6 = ui6.groupby(['Province' , 'City', 'Type', 'Garage', 'Bedrooms', 'Bathrooms','Year_Built'])
Real_Estate_PriceData_Groupedby_ProvinceCityHousetypeHouselayoutYearBuilt = ui6.mean()

#Clean The Sixth
ui7 = ui7.rename(columns={'Unnamed: 0': 'Fiscal/School Year'})
ui7= ui7.transpose()
ui7.columns = ui7.iloc[0]
ui7 = ui7.iloc[1:]
ui7['Start Date'] = '08-01-' + ui7.index.str[:4]
ui7['End Date'] = '07-31-' + ui7.index.str[-4:]

#Clean The Seventh
# Clean the annual data csvs and prepare to concatenate

ui8a['Year'] = '2015'
ui8a.set_index('Year')
ui8a = ui8a.rename(columns={
    'Economy (GDP per Capita)': 'Economy',
    'Health (Life Expectancy)' : 'Life Expectancy',
    'Trust (Government Corruption)' : 'Government Trust'

})

GlobalHappiness2015 = ui8a.drop(columns=['Standard Error'])
GlobalHappiness2015 = GlobalHappiness2015.set_index('Year')


ui8b['Year'] = '2016'
ui8b= ui8b.rename(columns={
    'Economy (GDP per Capita)': 'Economy',
    'Health (Life Expectancy)' : 'Life Expectancy',
     'Trust (Government Corruption)' : 'Government Trust',
    'Happiness.Rank' : 'Happiness Rank',
    'Happiness.Score' : 'Happiness Score',})
GlobalHappiness2016 = ui8b.drop(columns=['Lower Confidence Interval', 'Upper Confidence Interval'])
GlobalHappiness2016 = GlobalHappiness2016.set_index('Year')
    




ui8c['Year'] = '2017'
ui8c= ui8c.rename(columns={
    'Economy..GDP.per.Capita.': 'Economy',
    'Health..Life.Expectancy.' : 'Life Expectancy',
    'Trust..Government.Corruption.' : 'Government Trust',
    'Dystopia.Residual' : 'Dystopia Residual',
    'Happiness.Rank' : 'Happiness Rank',
    'Happiness.Score' : 'Happiness Score'})

GlobalHappiness2017 = ui8c.drop(columns=['Whisker.high', 'Whisker.low'])
GlobalHappiness2017 = GlobalHappiness2017.set_index('Year')


ui8d['Year'] = '2018'
ui8d= ui8d.rename(columns={
    'Overall rank': 'Happiness Rank',
    'Score': 'Happiness Score',
    'GDP per capita' : 'Economy',
    'Dystopia.Residual' : 'Dystopia Residual',
    'Healthy life expectancy' : 'Life Expectancy',
    'Freedom to make life choices' : 'Freedom',
    'Perceptions of corruption' : 'Government Trust',
    'Country or region' : 'Country'
})
GlobalHappiness2018 = ui8d.set_index('Year')




ui8e['Year'] = '2019'
ui8e= ui8e.rename(columns={
    'Overall rank': 'Happiness Rank',
    'Score': 'Happiness Score',
    'GDP per capita' : 'Economy',
    'Dystopia.Residual' : 'Dystopia Residual',
    'Healthy life expectancy' : 'Life Expectancy',
    'Freedom to make life choices' : 'Freedom',
    'Perceptions of corruption' : 'Government Trust',
    'Country or region' : 'Country'
})
GlobalHappiness2019 = ui8e.set_index('Year')


ui8f['Year'] = '2020'
ui8f = ui8f.drop(columns=['Social support','upperwhisker', 'lowerwhisker'])
ui8f= ui8f.rename(columns={
    'Explained by: Social support': 'Social support',
    'Ladder score': 'Happiness Score',
    'Explained by: Log GDP per capita' : 'Economy',
    'Dystopia.Residual' : 'Dystopia Residual',
    'Explained by: Healthy life expectancy' : 'Life Expectancy',
    'Explained by: Freedom to make life choices' : 'Freedom',
    'Explained by: Perceptions of corruption' : 'Government Trust',
    'Dystopia + residual' : 'Dystopia Residual',
    'Explained by: Generosity' : 'Generosity',
    'Regional indicator' : 'Region',
    'Country name' : 'Country'
})

ui8f = ui8f.drop(columns=['Standard error of ladder score', 'Logged GDP per capita', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption', 'Ladder score in Dystopia'])
GlobalHappiness2020 = ui8f.set_index('Year')



ui8g = ui8g.drop(columns=['upperwhisker', 'Social support', 'lowerwhisker', 'Standard error of ladder score', 'Logged GDP per capita', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption', 'Ladder score in Dystopia'])
ui8g['Year'] = '2021'
ui8g= ui8g.rename(columns={
    'Explained by: Social support': 'Social support',
    'Ladder score': 'Happiness Score',
    'Explained by: Log GDP per capita' : 'Economy',
    'Dystopia.Residual' : 'Dystopia Residual',
    'Explained by: Healthy life expectancy' : 'Life Expectancy',
    'Explained by: Freedom to make life choices' : 'Freedom',
    'Explained by: Perceptions of corruption' : 'Government Trust',
    'Dystopia + residual' : 'Dystopia Residual',
    'Explained by: Generosity' : 'Generosity',
     'Regional indicator' : 'Region',
    'Country name' : 'Country'
})

GlobalHappiness2021 = ui8g.set_index('Year')

columns_to_clean = [
    'Happiness score', 
    'Whisker-high', 
    'Whisker-low', 
    'Dystopia (1.83) + residual', 
    'Explained by: GDP per capita', 
    'Explained by: Social support', 
    'Explained by: Healthy life expectancy', 
    'Explained by: Freedom to make life choices', 
    'Explained by: Generosity', 
    'Explained by: Perceptions of corruption',
]

# Clean each column and parse out the commas
for column in columns_to_clean:
    ui8h[column] = ui8h[column].str.replace(',', '.').astype(float)


ui8h['Year'] = '2022'
ui8h = ui8h.drop(columns=['Whisker-high', 'Whisker-low'])
ui8h= ui8h.rename(columns={
    'Explained by: Social support': 'Social support',
    'Happiness score': 'Happiness Score',
    'Explained by: GDP per capita' : 'Economy',
    'Dystopia (1.83) + residual' : 'Dystopia Residual',
    'Explained by: Healthy life expectancy' : 'Life Expectancy',
    'Explained by: Freedom to make life choices' : 'Freedom',
    'Explained by: Perceptions of corruption' : 'Government Trust',
    'Explained by: Generosity' : 'Generosity',
    'RANK' : 'Happiness Rank'
})
GlobalHappiness2022 = ui8h.set_index('Year')


Global_Happiness_20152022 = pd.concat([GlobalHappiness2015, GlobalHappiness2016, GlobalHappiness2017, GlobalHappiness2018, GlobalHappiness2019, GlobalHappiness2020, GlobalHappiness2021, GlobalHappiness2022])
Global_Happiness_20152022 = Global_Happiness_20152022.groupby(['Year','Region', 'Country']).mean()

#Clean The Eighth
ui9a = ui9a.drop(ui9a.index[:4])
ui9a = ui9a.transpose()
ui9a.columns = ui9a.iloc[0]
ui9a = ui9a.iloc[1:]
ui9aYears=[]
ui9aQuarters=[]
for i in ui9a.index:
    ui9aYears.append(i[-4:])
    ui9aQuarters.append(i[:2])
ui9a['Years'] = ui9aYears
ui9a['Quarters'] = ui9aQuarters
ui9a = ui9a.reset_index()
ui9a = ui9a.drop(columns=['index','Quarters'])
columns_to_convert = ui9a.columns.difference(['Years'])
ui9a[columns_to_convert] = ui9a[columns_to_convert].apply(pd.to_numeric, errors='coerce')
ui9a['Years']=pd.to_datetime(ui9a['Years'])
ui9a['Years'] = ui9a['Years'].dt.year
Total_Household_Wealth = ui9a
Total_Household_Wealth['Profile'] = 'Total All Households'

ui9b = ui9b.drop(ui9b.index[:4])
ui9b = ui9b.transpose()
ui9b.columns = ui9b.iloc[0]
ui9b = ui9b.iloc[1:]
ui9bYears=[]
ui9bQuarters=[]
for i in ui9b.index:
    ui9bYears.append(i[-4:])
    ui9bQuarters.append(i[:2])
ui9b['Years'] = ui9bYears
ui9b['Quarters'] = ui9bQuarters
ui9b = ui9b.reset_index()
ui9b = ui9b.drop(columns=['index','Quarters'])
columns_to_convert = ui9b.columns.difference(['Years'])
ui9b[columns_to_convert] = ui9b[columns_to_convert].apply(pd.to_numeric, errors='coerce')
ui9b['Years']=pd.to_datetime(ui9b['Years'])
ui9b['Years'] = ui9b['Years'].dt.year
Highest_Income_Household_Wealth = ui9b
Highest_Income_Household_Wealth['Profile'] = 'Highest Income Households'


ui9c = ui9c.drop(ui9c.index[:4])
ui9c = ui9c.transpose()
ui9c.columns = ui9c.iloc[0]
ui9c = ui9c.iloc[1:]
ui9cYears=[]
ui9cQuarters=[]
for i in ui9c.index:
    ui9cYears.append(i[-4:])
    ui9cQuarters.append(i[:2])
ui9c['Years'] = ui9cYears
ui9c['Quarters'] = ui9cQuarters
ui9c = ui9c.reset_index()
ui9c = ui9c.drop(columns=['index','Quarters'])
columns_to_convert = ui9c.columns.difference(['Years'])
ui9c[columns_to_convert] = ui9c[columns_to_convert].apply(pd.to_numeric, errors='coerce')
ui9c['Years']= pd.to_datetime(ui9c['Years'], format='%Y')
ui9c['Years'] = ui9c['Years'].dt.year
Above65_Household_Wealth = ui9c
Above65_Household_Wealth['Profile'] = 'Household Wealth Above Age 65'

ui9d = ui9d.drop(ui9d.index[:4])
ui9d = ui9d.transpose()
ui9d.columns = ui9d.iloc[0]
ui9d = ui9d.iloc[1:]
ui9dYears=[]
ui9dQuarters=[]
for i in ui9d.index:
    ui9dYears.append(i[-4:])
    ui9dQuarters.append(i[:2])
ui9d['Years'] = ui9dYears
ui9d['Quarters'] = ui9dQuarters
ui9d = ui9d.reset_index()
ui9d = ui9d.drop(columns=['index','Quarters'])
columns_to_convert = ui9d.columns.difference(['Years'])
ui9d[columns_to_convert] = ui9d[columns_to_convert].apply(pd.to_numeric, errors='coerce')
ui9d['Years']=pd.to_datetime(ui9d['Years'])
ui9d['Years'] = ui9d['Years'].dt.year
Below64_Household_Wealth = ui9d
Below64_Household_Wealth['Profile'] = 'Household Wealth Below Age 64'

ui9e = ui9e.drop(ui9e.index[:4])
ui9e = ui9e.transpose()
ui9e.columns = ui9e.iloc[0]
ui9e = ui9e.iloc[1:]
ui9eYears=[]
ui9eQuarters=[]
for i in ui9e.index:
    ui9eYears.append(i[-4:])
    ui9eQuarters.append(i[:2])
ui9e['Years'] = ui9eYears
ui9e['Quarters'] = ui9eQuarters
ui9e = ui9e.reset_index()
ui9e = ui9e.drop(columns=['index','Quarters'])
columns_to_convert = ui9e.columns.difference(['Years'])
ui9e[columns_to_convert] = ui9e[columns_to_convert].apply(pd.to_numeric, errors='coerce')
ui9e['Years']=pd.to_datetime(ui9e['Years'])
ui9e['Years'] = ui9e['Years'].dt.year
Lowest_Income_Household_Wealth = ui9e
Lowest_Income_Household_Wealth['Profile'] = 'Lowest Income Household Wealth'

ui9f = ui9f.drop(ui9f.index[:4])
ui9f = ui9f.transpose()
ui9f.columns = ui9f.iloc[0]
ui9f = ui9f.iloc[1:]
ui9fYears=[]
ui9fQuarters=[]
for i in ui9f.index:
    ui9fYears.append(i[-4:])
    ui9fQuarters.append(i[:2])
ui9f['Years'] = ui9fYears
ui9f['Quarters'] = ui9fQuarters
ui9f = ui9f.reset_index()
ui9f = ui9f.drop(columns=['index','Quarters'])
columns_to_convert = ui9f.columns.difference(['Years'])
ui9f[columns_to_convert] = ui9f[columns_to_convert].apply(pd.to_numeric, errors='coerce')
ui9f['Years']=pd.to_datetime(ui9f['Years'])
ui9f['Years'] = ui9f['Years'].dt.year
Median_Income_Household_Wealth = ui9f
Median_Income_Household_Wealth['Profile'] = 'Median Income Household Wealth'


ui9g = ui9g.drop(ui9g.index[:4])
ui9g = ui9g.transpose()
ui9g.columns = ui9g.iloc[0]
ui9g = ui9g.iloc[1:]
ui9gYears=[]
ui9gQuarters=[]
for i in ui9g.index:
    ui9gYears.append(i[-4:])
    ui9gQuarters.append(i[:2])
ui9g['Years'] = ui9gYears
ui9g['Quarters'] = ui9gQuarters
ui9g = ui9g.reset_index()
ui9g = ui9g.drop(columns=['index','Quarters'])
columns_to_convert = ui9g.columns.difference(['Years'])
ui9g[columns_to_convert] = ui9g[columns_to_convert].apply(pd.to_numeric, errors='coerce')
ui9g['Years']=pd.to_datetime(ui9g['Years'])
ui9g['Years'] = ui9g['Years'].dt.year
Under35_Household_Wealth = ui9g
Under35_Household_Wealth['Profile'] = 'Household Wealth Below Age 35'

ui9h = ui9h.drop(ui9h.index[:4])
ui9h = ui9h.transpose()
ui9h.columns = ui9h.iloc[0]
ui9h = ui9h.iloc[1:]
ui9hYears=[]
ui9hQuarters=[]
for i in ui9h.index:
    ui9hYears.append(i[-4:])
    ui9hQuarters.append(i[:2])
ui9h['Years'] = ui9hYears
ui9h['Quarters'] = ui9hQuarters
ui9h = ui9h.reset_index()
ui9h = ui9h.drop(columns=['index','Quarters'])
columns_to_convert = ui9h.columns.difference(['Years'])
ui9h[columns_to_convert] = ui9h[columns_to_convert].apply(pd.to_numeric, errors='coerce')
ui9h['Years']=pd.to_datetime(ui9h['Years'])
ui9h['Years'] = ui9h['Years'].dt.year
Under44_Household_Wealth = ui9h
Under44_Household_Wealth['Profile'] = 'Household Wealth Below Age 44'

ui9i = ui9i.drop(ui9i.index[:4])
ui9i = ui9i.transpose()
ui9i.columns = ui9i.iloc[0]
ui9i = ui9i.iloc[1:]
ui9iYears=[]
ui9iQuarters=[]
for i in ui9i.index:
    ui9iYears.append(i[-4:])
    ui9iQuarters.append(i[:2])
ui9i['Years'] = ui9iYears
ui9i['Quarters'] = ui9iQuarters
ui9i = ui9i.reset_index()
ui9i = ui9i.drop(columns=['index','Quarters'])
columns_to_convert = ui9i.columns.difference(['Years'])
ui9i[columns_to_convert] = ui9i[columns_to_convert].apply(pd.to_numeric, errors='coerce')
ui9i['Years']=pd.to_datetime(ui9i['Years'])
ui9i['Years'] = ui9i['Years'].dt.year
Under54_Household_Wealth = ui9i
Under54_Household_Wealth['Profile'] = 'Household Wealth Below Age 54'

Canada_Household_Wealth = pd.concat([Under54_Household_Wealth, Under44_Household_Wealth,Under35_Household_Wealth,Median_Income_Household_Wealth,Lowest_Income_Household_Wealth, Below64_Household_Wealth, Above65_Household_Wealth, Highest_Income_Household_Wealth, Total_Household_Wealth])
Canada_Household_Wealth = Canada_Household_Wealth.groupby(['Years', 'Profile']).mean().fillna(0)

#Clean The Tenth
ui10a['Year'] = 2001
Canada_2001_Censusus= ui10a.groupby(['Year', 'Topic', 'Characteristic', 'Prov_Name']).mean()
Canada_2001_Census = Canada_2001_Censusus.rename(columns={'Prov_Name': 'Location'})

ui10b['Year'] = 2006
Canada_2006_Censusus= ui10b.groupby(['Year', 'Topic', 'Characteristic', 'Prov_Name']).mean()
Canada_2006_Census = Canada_2006_Censusus.rename(columns={'Prov_Name': 'Location'})

ui10c['Year'] = 2011
Canada_2011_Censusus= ui10c.groupby(['Year', 'Topic', 'Characteristic', 'Prov_Name']).mean()
Canada_2011_Census = Canada_2011_Censusus.rename(columns={'Prov_Name': 'Location'})

ui10d['Year'] = 2016
ui10d = ui10d.drop(columns=['CENSUS_YEAR', 'GEO_CODE (POR)', 'GEO_LEVEL', 'GNR', 'GNR_LF', 'DATA_QUALITY_FLAG', 'ALT_GEO_CODE', 'Member ID: Profile of Canada, Provinces and Territories (2247)', 'Notes: Profile of Canada, Provinces and Territories (2247)','Dim: Sex (3): Member ID: [2]: Male', 'Dim: Sex (3): Member ID: [3]: Female'])
Canada_2016_Censusus = ui10d.rename(columns={'GEO_NAME': 'Location', 'DIM: Profile of Canada, Provinces and Territories (2247)' : 'Characteristic', 'Dim: Sex (3): Member ID: [1]: Total - Sex' : 'Total'})
Canada_2016_Censusus['Total'] = pd.to_numeric(Canada_2016_Censusus['Total'], errors='coerce')
Canada_2016_Census = Canada_2016_Censusus.groupby(['Characteristic','Year','Location']).mean()

ui10e['Year'] = 2021
Canada_2021_Censusus= ui10e.rename(columns={'GEO_NAME': 'Location', 'CHARACTERISTIC_NAME' : 'Characteristic'})
Canada_2021_Censusus['Total'] = pd.to_numeric(Canada_2021_Censusus['Total'], errors='coerce')
Canada_2021_Census = Canada_2021_Censusus.groupby(['Characteristic','Year','Location']).mean()




CensusLogic1 = pd.concat([Canada_2001_Census, Canada_2006_Census, Canada_2011_Census])
CensusLogic1 = CensusLogic1.rename_axis(index={'Prov_Name': 'Location'})
CensusLogic2 = pd.concat([Canada_2016_Census, Canada_2021_Census])

In [5]:
#2021 Income Data Grouped by Location Age Group and Income Sources
income_2021_bylocation_byage_byincomesource

                                                                                         1 Year Median  \
Location              Age Group      Income Source Types
Abbotsford - Mission  15 to 24 years After-tax income                                          18800.0
                                     CPP/QPP - Disability benefits                                 NaN
                                     CPP/QPP - Retirement benefits                                 NaN
                                     CPP/QPP - Survivor benefits                                3060.0
                                     Canada Pension Plan (CPP) and Quebec Pension Pl...         3060.0
...                                                                                                ...
Yukon                 Total - Age    Provincial and territorial income taxes                    2760.0
                                     Social assistance benefits                                10000.0
                                     Total income                                              54800.0
                                     Wages, salaries and commissions                           54000.0
                                     Workers' compensation benefits                             3560.0

                                                                                         1 Year Average  \
Location              Age Group      Income Source Types
Abbotsford - Mission  15 to 24 years After-tax income                                           19720.0
                                     CPP/QPP - Disability benefits                                  0.0
                                     CPP/QPP - Retirement benefits                                  NaN
                                     CPP/QPP - Survivor benefits                                 2950.0
                                     Canada Pension Plan (CPP) and Quebec Pension Pl...          2920.0
...                                                                                                 ...
Yukon                 Total - Age    Provincial and territorial income taxes                     4200.0
                                     Social assistance benefits                                 11340.0
                                     Total income                                               64200.0
                                     Wages, salaries and commissions                            58800.0
                                     Workers' compensation benefits                             12360.0

                                                                                         1 Year Aggregate  \
Location              Age Group      Income Source Types
Abbotsford - Mission  15 to 24 years After-tax income                                            403000.0
                                     CPP/QPP - Disability benefits                                    0.0
                                     CPP/QPP - Retirement benefits                                    NaN
                                     CPP/QPP - Survivor benefits                                   1880.0
                                     Canada Pension Plan (CPP) and Quebec Pension Pl...            1880.0
...                                                                                                   ...
Yukon                 Total - Age    Provincial and territorial income taxes                     100400.0
                                     Social assistance benefits                                   24520.0
                                     Total income                                               2044000.0
                                     Wages, salaries and commissions                            1428000.0
                                     Workers' compensation benefits                                7250.0

                                                                                         Percent of Total Income (1 Year)  \
Location              Age Group      Income Source Types
Abbotsford - Mission  15 to 24 years After-tax income                                                                92.6
                                     CPP/QPP - Disability benefits                                                    0.0
                                     CPP/QPP - Retirement benefits                                                    NaN
                                     CPP/QPP - Survivor benefits                                                      0.4
                                     Canada Pension Plan (CPP) and Quebec Pension Pl...                               0.4
...                                                                                                                   ...
Yukon                 Total - Age    Provincial and territorial income taxes                                          4.9
                                     Social assistance benefits                                                       1.2
                                     Total income                                                                   100.0
                                     Wages, salaries and commissions                                                 70.0
                                     Workers' compensation benefits                                                   0.4

                                                                                         5 Year Median  \
Location              Age Group      Income Source Types
Abbotsford - Mission  15 to 24 years After-tax income                                          13000.0
                                     CPP/QPP - Disability benefits                                 0.0
                                     CPP/QPP - Retirement benefits                                 0.0
                                     CPP/QPP - Survivor benefits                                3040.0
                                     Canada Pension Plan (CPP) and Quebec Pension Pl...         3040.0
...                                                                                                ...
Yukon                 Total - Age    Provincial and territorial income taxes                    2700.0
                                     Social assistance benefits                                 7500.0
                                     Total income                                              49600.0
                                     Wages, salaries and commissions                           48400.0
                                     Workers' compensation benefits                             3560.0

                                                                                         5 Year Average  \
Location              Age Group      Income Source Types
Abbotsford - Mission  15 to 24 years After-tax income                                           16320.0
                                     CPP/QPP - Disability benefits                                  0.0
                                     CPP/QPP - Retirement benefits                                  0.0
                                     CPP/QPP - Survivor benefits                                 3130.0
                                     Canada Pension Plan (CPP) and Quebec Pension Pl...          3130.0
...                                                                                                 ...
Yukon                 Total - Age    Provincial and territorial income taxes                     3870.0
                                     Social assistance benefits                                  9510.0
                                     Total income                                               58250.0
                                     Wages, salaries and commissions                            54800.0
                                     Workers' compensation benefits                             11680.0

                                                                                         5 Year Aggregate  \
Location              Age Group      Income Source Types
Abbotsford - Mission  15 to 24 years After-tax income                                            292000.0
                                     CPP/QPP - Disability benefits                                    0.0
                                     CPP/QPP - Retirement benefits                                    0.0
                                     CPP/QPP - Survivor benefits                                   1520.0
                                     Canada Pension Plan (CPP) and Quebec Pension Pl...            1520.0
...                                                                                                   ...
Yukon                 Total - Age    Provincial and territorial income taxes                      77000.0
                                     Social assistance benefits                                   18000.0
                                     Total income                                               1624000.0
                                     Wages, salaries and commissions                            1216000.0
                                     Workers' compensation benefits                                6850.0

                                                                                         Percent of Total Income (5 Year)
Location              Age Group      Income Source Types
Abbotsford - Mission  15 to 24 years After-tax income                                                                93.2
                                     CPP/QPP - Disability benefits                                                    0.0
                                     CPP/QPP - Retirement benefits                                                    0.0
                                     CPP/QPP - Survivor benefits                                                      0.5
                                     Canada Pension Plan (CPP) and Quebec Pension Pl...                               0.5
...                                                                                                                   ...
Yukon                 Total - Age    Provincial and territorial income taxes                                          4.7
                                     Social assistance benefits                                                       1.1
                                     Total income                                                                   100.0
                                     Wages, salaries and commissions                                                 74.8
                                     Workers' compensation benefits                                                   0.4

[47808 rows x 8 columns]

In [6]:
#Household Liability and Debt Data Indexed By Date
household_liability_indexed_by_date

,Total Non-Mortgage,Non-Mortgage Chartered Banks,Non-Mortgage Personal Loans,Personal Loans for Automobiles,Credit Card Liabilities,Non-Mortgage Lines of credit,Non-Mortgage Lines Of Credit (Excluding Home Equity LsOc),Other personal loans,Unincorporated Business,Non-bank Non-Mortgage loans,...,Non-Residential Mortgages From Chartered Banks,Non-Residential Mortgages From Non-Banks,Non-Residential Mortgages from Government Loans,Non-Residential Mortgages from Non-Bank Financial Institutions,Non-Residential Mortgages from Credit unions and caisse populaires,Non-Residential Mortgages From Trust and Mortgage Loan Companies,Non-Residential Mortgages From Securitization Corporations,Non-Residential Mortgages From Other Financial Corporations,Non-Residential Mortgages From Other Lenders,Total Canada Credit Liability
Period,,,,,,,,,,,,,,,,,,,,,
January 1990,121607,77976,31781,0,9090,5550,1264,16523,15032,43631,...,373,2783,112,2319,221,88,0,2010,352,355663
February 1990,121405,77820,31769,0,8768,5695,1297,16585,15003,43585,...,374,2797,113,2332,221,87,0,2024,352,356410
March 1990,122357,78385,31878,0,8728,5841,1330,16828,15110,43972,...,381,2808,115,2334,222,89,0,2023,359,359518
April 1990,122780,78566,32099,0,8883,5989,1383,16630,14965,44214,...,390,2829,116,2354,221,90,0,2043,359,362686
May 1990,123345,78941,32316,0,9050,6022,1410,16699,14854,44404,...,396,2854,117,2377,223,91,0,2063,360,365890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
May 2023,734976,527514,122730,98264,96901,229425,69227,29942,48516,207462,...,3010,7069,601,5467,1950,8,69,3440,1001,2853053
June 2023,736427,529422,123563,99287,97850,229756,69705,29315,48938,207005,...,2939,7020,594,5423,1940,9,68,3406,1003,2865209
July 2023,737670,530576,124375,100074,99100,228717,69922,29339,49045,207094,...,2925,6999,591,5405,1948,9,68,3380,1003,2874448
August 2023,739923,531997,124971,100748,99971,228391,70285,29487,49177,207926,...,2882,6966,583,5380,1949,9,67,3355,1003,2885730
September 2023,742282,533439,125402,101031,101163,228438,70665,29125,49311,208843,...,2857,6937,577,5357,1951,9,67,3330,1003,2892254

In [7]:
#Income Per Capita Indexed By Date
Income_Per_Capita_indexed_by_date

            income
year
1970   3399.299037
1971   3768.297935
1972   4251.175484
1973   4804.463248
1974   5576.514583
1975   5998.144346
1976   7062.131392
1977   7100.126170
1978   7247.967035
1979   7602.912681
1980   8355.968120
1981   9434.390652
1982   9619.438377
1983  10416.536590
1984  10790.328720
1985  11018.955850
1986  11482.891530
1987  12974.806620
1988  15080.283450
1989  16426.725480
1990  16838.673200
1991  17266.097690
1992  16412.083090
1993  15875.586730
1994  15755.820270
1995  16369.317250
1996  16699.826680
1997  17310.757750
1998  16622.671870
1999  17581.024140
2000  18987.382410
2001  18601.397240
2002  19232.175560
2003  22739.426280
2004  25719.147150
2005  29198.055690
2006  32738.262900
2007  36144.481220
2008  37446.486090
2009  32755.176820
2010  38420.522890
2011  42334.711210
2012  42665.255970
2013  42676.468370
2014  41039.893600
2015  35175.188980
2016  34229.193630

In [8]:
#CPI Indexed By Date
Canada_CPI_Indexed_By_Date

,All-items,Food,Shelter,"Household operations, furnishings and equipment",Clothing and footwear,Transportation,Gasoline,Health and personal care,"Recreation, education and reading",Alcoholic beverages and tobacco products,All-items excluding food and energy,All-items excluding energy,Fresh fruit and vegetables,Energy,Goods,Services
Year,,,,,,,,,,,,,,,,
1981,49.5,54.3,50.0,58.6,61.8,45.2,50.9,49.7,46.2,27.8,48.8,50.0,57.2,46.8,53.8,44.9
1982,54.9,58.2,56.8,64.8,65.3,51.6,61.8,55.0,50.2,32.1,54.1,54.9,60.7,56.0,58.9,50.7
1983,58.1,60.4,60.9,68.3,67.9,54.2,65.6,58.8,53.5,36.1,57.4,58.0,60.7,60.4,62.1,53.9
1984,60.6,63.7,63.3,70.5,69.5,56.5,69.4,61.1,55.3,39.1,59.6,60.4,68.6,63.7,64.9,56.0
1985,63.0,65.5,65.6,72.3,71.5,59.2,73.5,63.2,57.7,42.8,62.0,62.7,67.6,67.3,67.5,58.2
1986,65.6,68.8,67.5,74.5,73.4,61.0,65.4,65.9,60.7,47.9,65.3,65.9,74.3,62.5,69.8,61.2
1987,68.5,71.8,70.5,76.7,76.5,63.3,68.5,69.3,63.7,51.1,68.3,68.9,78.1,64.1,72.6,64.1
1988,71.2,73.7,73.8,79.6,80.5,64.5,67.9,72.3,67.3,54.9,71.5,71.9,77.7,64.5,75.2,67.1
1989,74.8,76.5,78.1,82.5,83.7,67.8,72.1,75.5,70.3,59.9,75.5,75.6,79.1,66.7,78.4,70.9
1990,78.4,79.6,82.5,84.2,86.1,71.6,82.7,79.1,73.2,65.2,78.8,78.9,82.1,73.4,81.6,74.9
1991,82.8,83.4,86.3,87.4,94.3,72.9,81.5,84.7,78.3,76.4,83.4,83.4,89.8,77.0,85.7,79.6
1992,84.0,83.1,87.9,87.9,95.1,74.4,78.6,86.6,79.2,81.0,85.1,84.7,85.0,77.2,86.4,81.4
1993,85.6,84.5,89.1,88.7,96.0,76.8,77.4,88.9,81.1,82.2,86.8,86.3,89.0,78.1,87.8,83.1
1994,85.7,84.9,89.4,88.9,96.8,80.2,76.5,89.7,83.5,68.8,86.9,86.4,85.8,78.6,86.8,84.5
1995,87.6,86.9,90.4,90.6,96.7,84.3,80.1,89.6,86.7,68.7,88.8,88.4,84.4,79.6,88.4,86.7
1996,88.9,88.0,90.6,92.5,96.4,87.6,83.6,90.1,88.7,70.1,90.1,89.7,79.7,81.9,89.9,88.0
1997,90.4,89.4,90.8,93.7,97.7,90.3,85.2,91.7,91.0,72.3,91.5,91.0,80.0,83.9,91.2,89.5
1998,91.3,90.9,91.1,95.1,98.8,89.6,77.9,93.6,93.0,74.9,92.7,92.3,86.7,80.5,91.4,91.1
1999,92.9,92.0,92.3,95.8,100.1,92.6,84.9,95.4,94.7,76.5,94.0,93.6,86.8,85.0,93.1,92.6
2000,95.4,93.3,95.6,96.7,100.3,97.2,103.5,97.0,97.0,79.0,95.5,95.0,85.6,98.8,96.0,94.8
2001,97.8,97.4,99.1,98.6,100.7,97.3,100.8,98.9,98.4,85.0,97.3,97.3,93.6,102.0,98.4,97.1
2002,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
2003,102.8,101.7,103.2,100.7,98.2,105.2,106.4,101.4,100.8,110.1,102.5,102.4,94.1,107.9,101.9,103.6
2004,104.7,103.8,105.8,101.2,98.0,107.7,117.6,102.8,101.1,116.0,103.9,103.8,92.9,115.2,103.4,105.9
2005,107.0,106.4,109.2,101.7,97.6,112.0,132.6,104.6,100.8,119.1,105.3,105.4,92.6,126.3,105.8,108.2
2006,109.1,108.9,113.1,102.2,95.8,115.2,139.8,105.9,100.6,121.7,106.9,107.2,96.6,132.8,107.1,111.1
2007,111.5,111.8,116.9,103.2,95.7,117.1,146.1,107.3,101.8,125.5,109.0,109.5,97.0,135.9,108.0,114.8
2008,114.1,115.7,122.0,104.6,93.8,119.5,164.7,108.8,102.2,127.5,110.3,111.3,98.5,149.3,109.4,118.7
2009,114.4,121.4,121.6,107.3,93.4,113.1,135.8,112.1,103.1,130.7,111.5,113.3,106.5,129.2,107.6,121.2
2010,116.5,123.1,123.3,108.8,91.6,118.0,148.2,115.1,104.0,133.1,112.9,114.8,103.6,137.8,109.2,123.7
2011,119.9,127.7,125.6,110.9,91.9,125.6,177.8,117.1,105.3,135.6,114.7,117.0,111.1,154.7,112.9,126.7
2012,121.7,130.8,127.1,113.0,92.0,128.1,182.3,118.7,105.9,137.6,116.2,118.8,109.6,157.3,114.0,129.3
2013,122.8,132.4,128.7,114.4,92.1,129.0,183.4,118.3,106.2,140.4,117.2,119.9,114.4,159.6,114.6,131.0
2014,125.2,135.5,132.2,116.6,93.2,130.4,183.8,119.0,107.4,146.6,119.0,122.0,120.3,165.3,116.5,133.7
2015,126.6,140.5,133.7,119.7,94.6,126.5,153.4,120.5,109.4,152.0,121.2,124.6,129.1,149.5,116.8,136.4
2016,128.4,142.6,135.8,121.7,94.4,127.9,144.2,122.2,111.3,156.8,123.5,126.9,134.2,145.0,117.9,138.9
2017,130.4,142.7,138.1,121.9,93.7,132.9,161.2,124.3,114.0,161.1,125.5,128.5,130.8,152.7,118.9,142.0
2018,133.4,145.3,140.9,123.2,94.5,139.1,181.5,125.9,115.3,167.9,127.9,131.0,135.8,162.9,121.1,145.8

In [9]:
#Housing Price Data Grouped By Province, City, House Type, House Layout and Year Built
Real_Estate_PriceData_Groupedby_ProvinceCityHousetypeHouselayoutYearBuilt

                                                                      Price  \
Province City      Type      Garage Bedrooms Bathrooms Year_Built
AB       Calgary   Apartment 0      1        1         1953        382945.0
                                             2         1974        831482.0
                                             3         1952        801441.0
                                    2        1         1955        560557.0
                                                       2002        649357.0
...                                                                     ...
QC       Vancouver House     1      5        2         1979        226723.0
                                                       1980        273183.0
                                                       1984        307781.0
                                             3         2003        750609.0
                                                       2008        701797.0

                                                                     SqFt  \
Province City      Type      Garage Bedrooms Bathrooms Year_Built
AB       Calgary   Apartment 0      1        1         1953        2665.0
                                             2         1974        3461.0
                                             3         1952        1722.0
                                    2        1         1955        3582.0
                                                       2002        3652.0
...                                                                   ...
QC       Vancouver House     1      5        2         1979        1443.0
                                                       1980        3822.0
                                                       1984        2930.0
                                             3         2003         987.0
                                                       2008        3921.0

                                                                   Lot_Area
Province City      Type      Garage Bedrooms Bathrooms Year_Built
AB       Calgary   Apartment 0      1        1         1953          3953.0
                                             2         1974          7858.0
                                             3         1952          9572.0
                                    2        1         1955          6536.0
                                                       2002          5722.0
...                                                                     ...
QC       Vancouver House     1      5        2         1979          7273.0
                                                       1980          2300.0
                                                       1984          5730.0
                                             3         2003          3442.0
                                                       2008          2702.0

[4900 rows x 3 columns]

In [10]:
#Global Happiness By year, country, region
Global_Happiness_20152022

                                                Happiness Rank  \
Year Region                     Country
2015 Australia and New Zealand  Australia                 10.0
                                New Zealand                9.0
     Central and Eastern Europe Albania                   95.0
                                Armenia                  127.0
                                Azerbaijan                80.0
...                                                        ...
2021 Western Europe             Portugal                   NaN
                                Spain                      NaN
                                Sweden                     NaN
                                Switzerland                NaN
                                United Kingdom             NaN

                                                Happiness Score  Economy  \
Year Region                     Country
2015 Australia and New Zealand  Australia                 7.284  1.33358
                                New Zealand               7.286  1.25018
     Central and Eastern Europe Albania                   4.959  0.87867
                                Armenia                   4.350  0.76821
                                Azerbaijan                5.212  1.02389
...                                                         ...      ...
2021 Western Europe             Portugal                  5.929  1.32300
                                Spain                     6.491  1.37500
                                Sweden                    7.363  1.47800
                                Switzerland               7.571  1.56600
                                United Kingdom            7.064  1.42300

                                                 Family  Life Expectancy  \
Year Region                     Country
2015 Australia and New Zealand  Australia       1.30923          0.93156
                                New Zealand     1.31967          0.90837
     Central and Eastern Europe Albania         0.80434          0.81325
                                Armenia         0.77711          0.72990
                                Azerbaijan      0.93793          0.64045
...                                                 ...              ...
2021 Western Europe             Portugal            NaN          0.76000
                                Spain               NaN          0.82600
                                Sweden              NaN          0.76300
                                Switzerland         NaN          0.81600
                                United Kingdom      NaN          0.75700

                                                Freedom  Government Trust  \
Year Region                     Country
2015 Australia and New Zealand  Australia       0.65124           0.35637
                                New Zealand     0.63938           0.42922
     Central and Eastern Europe Albania         0.35733           0.06413
                                Armenia         0.19847           0.03900
                                Azerbaijan      0.37030           0.16065
...                                                 ...               ...
2021 Western Europe             Portugal        0.62100           0.03300
                                Spain           0.46200           0.12400
                                Sweden          0.68500           0.44800
                                Switzerland     0.65300           0.41300
                                United Kingdom  0.58000           0.30600

                                                Generosity  Dystopia Residual  \
Year Region                     Country
2015 Australia and New Zealand  Australia          0.43562            2.26646
                                New Zealand        0.47501            2.26425
     Central and Eastern Europe Albania            0.14272            1.89894
                                Armenia            0.07855            1.75873
                                Azerbaijan         0.07799            2.00073
...                                                    ...                ...
2021 Western Europe             Portugal           0.02900            2.22500
                                Spain              0.13500            2.51300
                                Sweden             0.24400            2.68300
                                Switzerland        0.20400            2.83900
                                United Kingdom     0.34000            2.59600

                                                Social support
Year Region                     Country
2015 Australia and New Zealand  Australia                  NaN
                                New Zealand                NaN
     Central and Eastern Europe Albania                    NaN
                                Armenia                    NaN
                                Azerbaijan                 NaN
...                                                        ...
2021 Western Europe             Portugal                 0.939
                                Spain                    1.057
                                Sweden                   1.062
                                Switzerland              1.079
                                United Kingdom           1.062

[617 rows x 10 columns]

In [11]:
#Canada Household Wealth Data By Year and Profile
Canada_Household_Wealth

                                      Life insurance and pensions as a share of total assets 3  \
Years Profile
1997  Household Wealth Below Age 64                                                0.00
1998  Household Wealth Below Age 64                                                0.00
1999  Household Wealth Below Age 64                                                0.00
2000  Household Wealth Below Age 64                                                0.00
2001  Household Wealth Below Age 64                                                0.00
...                                                                                 ...
2023  Household Wealth Below Age 44                                               11.55
      Household Wealth Below Age 54                                               16.50
      Lowest Income Household Wealth                                               9.55
      Median Income Household Wealth                                              20.25
      Total All Households                                                         0.00

                                      Other financial assets as a share of total assets 4  \
Years Profile
1997  Household Wealth Below Age 64                                                0.00
1998  Household Wealth Below Age 64                                                0.00
1999  Household Wealth Below Age 64                                                0.00
2000  Household Wealth Below Age 64                                                0.00
2001  Household Wealth Below Age 64                                                0.00
...                                                                                 ...
2023  Household Wealth Below Age 44                                               28.00
      Household Wealth Below Age 54                                               32.05
      Lowest Income Household Wealth                                              31.90
      Median Income Household Wealth                                              26.50
      Total All Households                                                         0.00

                                      Non-financial assets as a share of total assets  \
Years Profile
1997  Household Wealth Below Age 64                                              0.00
1998  Household Wealth Below Age 64                                              0.00
1999  Household Wealth Below Age 64                                              0.00
2000  Household Wealth Below Age 64                                              0.00
2001  Household Wealth Below Age 64                                              0.00
...                                                                               ...
2023  Household Wealth Below Age 44                                             60.45
      Household Wealth Below Age 54                                             51.45
      Lowest Income Household Wealth                                            58.60
      Median Income Household Wealth                                            53.25
      Total All Households                                                      49.05

                                      Real estate as a share of total assets  \
Years Profile
1997  Household Wealth Below Age 64                                     0.00
1998  Household Wealth Below Age 64                                     0.00
1999  Household Wealth Below Age 64                                     0.00
2000  Household Wealth Below Age 64                                     0.00
2001  Household Wealth Below Age 64                                     0.00
...                                                                      ...
2023  Household Wealth Below Age 44                                    53.70
      Household Wealth Below Age 54                                    46.70
      Lowest Income Household Wealth                                   52.95
      Median Income Household Wealth                                   47.40
      Total All Households                                             44.10

                                      Other non-financial assets as a share of total assets 5  \
Years Profile
1997  Household Wealth Below Age 64                                                 0.0
1998  Household Wealth Below Age 64                                                 0.0
1999  Household Wealth Below Age 64                                                 0.0
2000  Household Wealth Below Age 64                                                 0.0
2001  Household Wealth Below Age 64                                                 0.0
...                                                                                 ...
2023  Household Wealth Below Age 44                                                 6.7
      Household Wealth Below Age 54                                                 4.8
      Lowest Income Household Wealth                                                5.6
      Median Income Household Wealth                                                5.9
      Total All Households                                                          0.0

                                      Liabilities as a share of total assets  \
Years Profile
1997  Household Wealth Below Age 64                                     0.00
1998  Household Wealth Below Age 64                                     0.00
1999  Household Wealth Below Age 64                                     0.00
2000  Household Wealth Below Age 64                                     0.00
2001  Household Wealth Below Age 64                                     0.00
...                                                                      ...
2023  Household Wealth Below Age 44                                    31.65
      Household Wealth Below Age 54                                    19.40
      Lowest Income Household Wealth                                   19.25
      Median Income Household Wealth                                   19.45
      Total All Households                                             15.40

                                      Mortgage liabilities as a share of total assets  \
Years Profile
1997  Household Wealth Below Age 64                                              0.00
1998  Household Wealth Below Age 64                                              0.00
1999  Household Wealth Below Age 64                                              0.00
2000  Household Wealth Below Age 64                                              0.00
2001  Household Wealth Below Age 64                                              0.00
...                                                                               ...
2023  Household Wealth Below Age 44                                             25.45
      Household Wealth Below Age 54                                             14.75
      Lowest Income Household Wealth                                            14.60
      Median Income Household Wealth                                            14.15
      Total All Households                                                      11.30

                                      Other liabilities as a share of total assets 6  \
Years Profile
1997  Household Wealth Below Age 64                                              0.0
1998  Household Wealth Below Age 64                                              0.0
1999  Household Wealth Below Age 64                                              0.0
2000  Household Wealth Below Age 64                                              0.0
2001  Household Wealth Below Age 64                                              0.0
...                                                                              ...
2023  Household Wealth Below Age 44                                              6.2
      Household Wealth Below Age 54                                              4.7
      Lowest Income Household Wealth                                             4.7
      Median Income Household Wealth                                             5.3
      Total All Households                                                       0.0

                                      Liabilities as a share of net worth  \
Years Profile
1997  Household Wealth Below Age 64                                  0.00
1998  Household Wealth Below Age 64                                  0.00
1999  Household Wealth Below Age 64                                  0.00
2000  Household Wealth Below Age 64                                  0.00
2001  Household Wealth Below Age 64                                  0.00
...                                                                   ...
2023  Household Wealth Below Age 44                                 46.40
      Household Wealth Below Age 54                                 24.10
      Lowest Income Household Wealth                                23.85
      Median Income Household Wealth                                24.15
      Total All Households                                          18.20

                                      Assets as a share of net worth  ...  \
Years Profile                                                         ...
1997  Household Wealth Below Age 64                             0.00  ...
1998  Household Wealth Below Age 64                             0.00  ...
1999  Household Wealth Below Age 64                             0.00  ...
2000  Household Wealth Below Age 64                             0.00  ...
2001  Household Wealth Below Age 64                             0.00  ...
...                                                              ...  ...
2023  Household Wealth Below Age 44                           146.40  ...
      Household Wealth Below Age 54                           124.10  ...
      Lowest Income Household Wealth                          123.85  ...
      Median Income Household Wealth                          124.15  ...
      Total All Households                                    118.20  ...

                                      Other services (except public administration)  \
Years Profile
1997  Household Wealth Below Age 64                                           12.81
1998  Household Wealth Below Age 64                                           13.02
1999  Household Wealth Below Age 64                                           13.12
2000  Household Wealth Below Age 64                                           14.00
2001  Household Wealth Below Age 64                                           14.37
...                                                                             ...
2023  Household Wealth Below Age 44                                            0.00
      Household Wealth Below Age 54                                            0.00
      Lowest Income Household Wealth                                           0.00
      Median Income Household Wealth                                           0.00
      Total All Households                                                     0.00

                                      Public administration  \
Years Profile
1997  Household Wealth Below Age 64                   19.43
1998  Household Wealth Below Age 64                   19.75
1999  Household Wealth Below Age 64                   20.62
2000  Household Wealth Below Age 64                   21.33
2001  Household Wealth Below Age 64                   22.11
...                                                     ...
2023  Household Wealth Below Age 44                    0.00
      Household Wealth Below Age 54                    0.00
      Lowest Income Household Wealth                   0.00
      Median Income Household Wealth                   0.00
      Total All Households                             0.00

                                      Life insurance and pensions as a share of total assets 1  \
Years Profile
1997  Household Wealth Below Age 64                                                0.00
1998  Household Wealth Below Age 64                                                0.00
1999  Household Wealth Below Age 64                                                0.00
2000  Household Wealth Below Age 64                                                0.00
2001  Household Wealth Below Age 64                                                0.00
...                                                                                 ...
2023  Household Wealth Below Age 44                                                0.00
      Household Wealth Below Age 54                                                0.00
      Lowest Income Household Wealth                                               0.00
      Median Income Household Wealth                                               0.00
      Total All Households                                                        15.75

                                      Other financial assets as a share of total assets 2  \
Years Profile
1997  Household Wealth Below Age 64                                                 0.0
1998  Household Wealth Below Age 64                                                 0.0
1999  Household Wealth Below Age 64                                                 0.0
2000  Household Wealth Below Age 64                                                 0.0
2001  Household Wealth Below Age 64                                                 0.0
...                                                                                 ...
2023  Household Wealth Below Age 44                                                 0.0
      Household Wealth Below Age 54                                                 0.0
      Lowest Income Household Wealth                                                0.0
      Median Income Household Wealth                                                0.0
      Total All Households                                                         35.2

                                      Other non-financial assets as a share of total assets 3  \
Years Profile
1997  Household Wealth Below Age 64                                                 0.0
1998  Household Wealth Below Age 64                                                 0.0
1999  Household Wealth Below Age 64                                                 0.0
2000  Household Wealth Below Age 64                                                 0.0
2001  Household Wealth Below Age 64                                                 0.0
...                                                                                 ...
2023  Household Wealth Below Age 44                                                 0.0
      Household Wealth Below Age 54                                                 0.0
      Lowest Income Household Wealth                                                0.0
      Median Income Household Wealth                                                0.0
      Total All Households                                                          5.0

                                      Other liabilities as a share of total assets 4  \
Years Profile
1997  Household Wealth Below Age 64                                              0.0
1998  Household Wealth Below Age 64                                              0.0
1999  Household Wealth Below Age 64                                              0.0
2000  Household Wealth Below Age 64                                              0.0
2001  Household Wealth Below Age 64                                              0.0
...                                                                              ...
2023  Household Wealth Below Age 44                                              0.0
      Household Wealth Below Age 54                                              0.0
      Lowest Income Household Wealth                                             0.0
      Median Income Household Wealth                                             0.0
      Total All Households                                                       4.1

                                      Owner's equity as a share of real estate 5  \
Years Profile
1997  Household Wealth Below Age 64                                          0.0
1998  Household Wealth Below Age 64                                          0.0
1999  Household Wealth Below Age 64                                          0.0
2000  Household Wealth Below Age 64                                          0.0
2001  Household Wealth Below Age 64                                          0.0
...                                                                          ...
2023  Household Wealth Below Age 44                                          0.0
      Household Wealth Below Age 54                                          0.0
      Lowest Income Household Wealth                                         0.0
      Median Income Household Wealth                                         0.0
      Total All Households                                                  74.4

                                      Real estate as a share of disposable income 6  \
Years Profile
1997  Household Wealth Below Age 64                                            0.00
1998  Household Wealth Below Age 64                                            0.00
1999  Household Wealth Below Age 64                                            0.00
2000  Household Wealth Below Age 64                                            0.00
2001  Household Wealth Below Age 64                                            0.00
...                                                                             ...
2023  Household Wealth Below Age 44                                            0.00
      Household Wealth Below Age 54                                            0.00
      Lowest Income Household Wealth                                           0.00
      Median Income Household Wealth                                           0.00
      Total All Households                                                   552.35

                                      Net worth as a share of disposable income 6  \
Years Profile
1997  Household Wealth Below Age 64                                          0.00
1998  Household Wealth Below Age 64                                          0.00
1999  Household Wealth Below Age 64                                          0.00
2000  Household Wealth Below Age 64                                          0.00
2001  Household Wealth Below Age 64                                          0.00
...                                                                           ...
2023  Household Wealth Below Age 44                                          0.00
      Household Wealth Below Age 54                                          0.00
      Lowest Income Household Wealth                                         0.00
      Median Income Household Wealth                                         0.00
      Total All Households                                                1059.55

                                      Debt to disposable income ratio 6
Years Profile
1997  Household Wealth Below Age 64                                0.00
1998  Household Wealth Below Age 64                                0.00
1999  Household Wealth Below Age 64                                0.00
2000  Household Wealth Below Age 64                                0.00
2001  Household Wealth Below Age 64                                0.00
...                                                                 ...
2023  Household Wealth Below Age 44                                0.00
      Household Wealth Below Age 54                                0.00
      Lowest Income Household Wealth                               0.00
      Median Income Household Wealth                               0.00

In [12]:
#Census Data Organized 2001 - 2011
CensusLogic1

                                                                                                         Total
Year Topic                          Characteristic                                Location
2001 Aboriginal Population             Aboriginal identity population             Alberta             156220.0
                                                                                  British Columbia    170025.0
                                                                                  Canada              976305.0
                                                                                  Manitoba            150040.0
                                                                                  New Brunswick        16990.0
...                                                                                                        ...
2011 Population and dwelling counts Population density per square kilometre       Canada                   3.7
                                    Population in 2006                            Canada            31612897.0
                                    Population in 2011                            Canada            33476688.0
                                    Private dwellings occupied by usual residents Canada            13320614.0
                                    Total private dwellings                       Canada            14569633.0

[8806 rows x 1 columns]

In [13]:
#Census Data Organized 2016 - 2021
CensusLogic2

                                                 Total
Characteristic     Year Location
$10,000 to $14,999 2016 Alberta                18335.0
                        British Columbia       56262.5
                        Canada                377627.5
                        Manitoba               11655.0
                        New Brunswick           6907.5
...                                                ...
Unemployment rate  2021 Ontario                   12.2
                        Prince Edward Island      10.3
                        Quebec                     7.6
                        Saskatchewan               8.4
                        Yukon                      6.8

[36442 rows x 1 columns]

# User Input Machine Learning Models

In [56]:
#Declutter Variables
columns_to_convert = [
    'Total Non-Mortgage', 'Non-Mortgage Chartered Banks',
    'Non-Mortgage Personal Loans', 'Personal Loans for Automobiles',
    'Credit Card Liabilities', 'Non-Mortgage Lines of credit',
    'Non-Mortgage Lines Of Credit (Excluding Home Equity LsOc)',
    'Other personal loans', 'Unincorporated Business',
    'Non-bank Non-Mortgage loans', 'Government Non-Mortgage Loans',
    'Non-bank Financial Institutions Non-Mortgage Loans',
    'Non-Mortgage Loans From Credit unions and caisse populaires',
    'Non-Mortgage Loans From Trust and Mortgage Loan Companies',
    'Non-Mortgage Securities From Securitization Corporations',
    'Other Non-Mortgage financial corporations',
    'Other Non-Mortgage Lenders', 'Mortgage loans',
    'Residential Mortgages Total',
    'Residential Mortgages From Chartered Banks',
    'Residential Mortgages From Non-Banks',
    'Residential Mortgages from Government Loans',
    'Residential Mortgages from Non-Bank Financial Institutions',
    'Residential Mortgages from Credit unions and caisse populaires',
    'Residential Mortgages From Trust and Mortgage Loan Companies',
    'Residential Mortgages From Securitization Corporations',
    'Residential Mortgages From Other Financial Corporations',
    'Residential Mortgages From Other Lenders',
    'Non-Residential Mortgages Total',
    'Non-Residential Mortgages From Chartered Banks',
    'Non-Residential Mortgages From Non-Banks',
    'Non-Residential Mortgages from Government Loans',
    'Non-Residential Mortgages from Non-Bank Financial Institutions',
    'Non-Residential Mortgages from Credit unions and caisse populaires',
    'Non-Residential Mortgages From Trust and Mortgage Loan Companies',
    'Non-Residential Mortgages From Securitization Corporations',
    'Non-Residential Mortgages From Other Financial Corporations',
    'Non-Residential Mortgages From Other Lenders',
    'Total Canada Credit Liability'
]

income_profiler = ['AgeGroup_25 to 34 years',
       'AgeGroup_25 to 54 years', 'AgeGroup_25 to 64 years',
       'AgeGroup_35 to 44 years', 'AgeGroup_45 to 54 years',
       'AgeGroup_55 to 64 years', 'AgeGroup_65 years and over',
       'AgeGroup_Total - Age', '1 Year Average', 'Income Source Tpes_CPP/QPP - Disability benefits',
       'Income Source Tpes_CPP/QPP - Retirement benefits',
       'Income Source Tpes_CPP/QPP - Survivor benefits',
       'Income Source Tpes_Canada Pension Plan (CPP) and Quebec Pension Plan (QPP) benefits',
       'Income Source Tpes_Canada workers benefit (CWB)',
       'Income Source Tpes_Child benefits',
       'Income Source Tpes_EI - Other benefits',
       'Income Source Tpes_EI - Regular benefits',
       'Income Source Tpes_Employment Insurance (EI) benefits',
       'Income Source Tpes_Employment income',
       'Income Source Tpes_Federal child benefits',
       'Income Source Tpes_Goods and Services Tax (GST) credit and Harmonized Sales Tax (HST) credit',
       'Income Source Tpes_Government transfers',
       'Income Source Tpes_Government transfers not included elsewhere',
       'Income Source Tpes_Guaranteed Income Supplement (GIS) and spousal allowance',
       'Income Source Tpes_Income taxes',
       'Income Source Tpes_Investment income',
       'Income Source Tpes_Market income',
       'Income Source Tpes_Market income not included elsewhere',
       'Income Source Tpes_Net federal income tax',
       'Income Source Tpes_Net self-employment income',
       'Income Source Tpes_Old Age Security pension (OAS)',
       'Income Source Tpes_Old Age Security pension (OAS) and Guaranteed Income Supplement (GIS)',
       'Income Source Tpes_Other government transfers',
       'Income Source Tpes_Private retirement income',
       'Income Source Tpes_Provincial and territorial child benefits',
       'Income Source Tpes_Provincial and territorial income taxes',
       'Income Source Tpes_Social assistance benefits',
       'Income Source Tpes_Total income',
       'Income Source Tpes_Wages, salaries and commissions',
       "Income Source Tpes_Workers' compensation benefits"]

targetcolumns = [col for col in AgeClassificationLogic.columns if col.startswith('Column Name')]

Income_Profile_Variables = ['Years',
 'Life insurance and pensions as a share of total assets 3',
 'Other financial assets as a share of total assets 4',
 'Non-financial assets as a share of total assets',
 'Real estate as a share of total assets',
 'Other non-financial assets as a share of total assets 5',
 'Liabilities as a share of total assets',
 'Mortgage liabilities as a share of total assets',
 'Other liabilities as a share of total assets 6',
 'Liabilities as a share of net worth',
 'Assets as a share of net worth',
 'Financial assets as a share of net worth',
 'Financial assets to non-financial assets ratio',
 "Owner's equity as a share of real estate 7",
 'Real estate as a share of disposable income 8',
 'Net worth as a share of disposable income 8',
 'Debt to disposable income ratio 8',
 'Financial assets as a share of total assets',
 'Agriculture 8',
 'Forestry, fishing, mining, quarrying, oil and gas 9 10',
 'Utilities',
 'Construction',
 'Manufacturing',
 'Services-producing sector 11',
 'Wholesale and retail trade',
 'Transportation and warehousing',
 'Finance, insurance, real estate, rental and leasing',
 'Professional, scientific and technical services',
 'Business, building and other support services 12',
 'Educational services',
 'Health care and social assistance',
 'Information, culture and recreation',
 'Accommodation and food services',
 'Other services (except public administration)',
 'Public administration',
 'Life insurance and pensions as a share of total assets 1',
 'Other financial assets as a share of total assets 2',
 'Other non-financial assets as a share of total assets 3',
 'Other liabilities as a share of total assets 4',
 "Owner's equity as a share of real estate 5",
 'Real estate as a share of disposable income 6',
 'Net worth as a share of disposable income 6',
 'Debt to disposable income ratio 6']

In [39]:
#Income Profiling

variable3 = Canada_Household_Wealth.groupby(['Profile', 'Years']).mean()
rows_to_exclude2 = [('Household Wealth Below Age 64', year) for year in range(1997, 2024)]
Canada_Household_Wealth_By_Income = variable3[~variable3.index.isin(rows_to_exclude2)]
Canada_Household_Wealth_By_Income.reset_index(inplace=True)

incomeX = Canada_Household_Wealth_By_Income.drop(columns=['Profile'])
incomey = Canada_Household_Wealth_By_Income['Profile'].astype(str) 
incomeX_train, incomeX_test, incomey_train, incomey_test = train_test_split(incomeX, incomey, test_size=0.2, random_state=42)
initiator = RandomForestClassifier()
initiator.fit(incomeX_train, incomey_train)
income_y_pred = initiator.predict(incomeX_test)
# Evaluate the model
incomeaccuracy = accuracy_score(incomey_test, income_y_pred)
incomereport = classification_report(incomey_test, income_y_pred)


print(f'Income Machine Accuracy: {incomeaccuracy}')
print(f'Income Machine Classification Report:\n{incomereport}')

Income Machine Accuracy: 1.0
Income Machine Classification Report:
                                precision    recall  f1-score   support

     Highest Income Households       1.00      1.00      1.00         5
 Household Wealth Above Age 65       1.00      1.00      1.00         2
 Household Wealth Below Age 35       1.00      1.00      1.00         3
 Household Wealth Below Age 44       1.00      1.00      1.00         5
 Household Wealth Below Age 54       1.00      1.00      1.00         3
Lowest Income Household Wealth       1.00      1.00      1.00         2
Median Income Household Wealth       1.00      1.00      1.00         2
          Total All Households       1.00      1.00      1.00         1

                      accuracy                           1.00        23
                     macro avg       1.00      1.00      1.00        23
                  weighted avg       1.00      1.00      1.00        23

In [71]:
#Age Profiling
AgeClassificationLogic = ui11.fillna(0)

AgeClassificationLogic = AgeClassificationLogic.transpose()
AgeClassificationLogic.reset_index(inplace=True)
AgeClassificationLogic.columns = AgeClassificationLogic.iloc[0]
AgeClassificationLogic = pd.get_dummies(AgeClassificationLogic)
AgeClassificationLogic = AgeClassificationLogic[1:]
ageX = AgeClassificationLogic[targetcolumns]
agey = AgeClassificationLogic.drop(columns= targetcolumns)
agey = agey.apply(pd.to_numeric, errors='coerce')
agey = agey.dropna()
ageX_train, ageX_test, agey_train, agey_test = train_test_split(ageX, agey, test_size=0.2, random_state=15)
agitator = StandardScaler()
ageX_train_scaled = agitator.fit_transform(ageX_train)
ageX_test_scaled = agitator.transform(ageX_test)
ageknn = KNeighborsRegressor(n_neighbors=3)
ageknn.fit(ageX_train_scaled, agey_train)

#Model Evaluation
agey_pred = ageknn.predict(ageX_test_scaled)
agemae = mean_absolute_error(agey_test, agey_pred)
print(f'Profile Machine Mean Absolute Error: {agemae}')
ager2 = r2_score(agey_test, agey_pred)
print(f'Profile Machine R-squared: {ager2}')

#Age Profile Comparison
ui1

#Age Profile Comparison
variable1 = Canada_Household_Wealth.groupby(['Profile']).mean()
rows_to_exclude = ['Highest Income Households', 'Lowest Income Household Wealth', 'Median Income Household Wealth']
Canada_Household_Wealth_By_Age = variable1[~variable1.index.isin(rows_to_exclude)]
Canada_Household_Wealth_By_Age.reset_index(inplace=True)

#Historical Data
CensusLogic1ByAge = CensusLogic1.xs('Age Characteristics of the Population', level='Topic')
CensusLogic1ByAge.reset_index(inplace=True)

Profile Machine Mean Absolute Error: 0.06589147286821706
Profile Machine R-squared: 0.5780289180763476

In [114]:
ageX_test.to_csv("Test Data.csv")

In [82]:
#Historical Data
CensusLocation2 = CensusLogic2.groupby(['Year', 'Location']).mean()
CensusLocation1 = CensusLogic1.groupby(['Year', 'Location']).mean()

#Location Population Comparison
CensusLocationmerge = pd.concat([CensusLocation1, CensusLocation2]).groupby(['Location']).mean()

#Historical Data
GlobalHappinessByCountry = Global_Happiness_20152022.groupby(['Country', 'Year']).mean()
Canada_Happiness_20152022 = Global_Happiness_20152022.xs('Canada', level='Country')

#Average House Prices Per City
RealEstatePriceDataByCity = Real_Estate_PriceData_Groupedby_ProvinceCityHousetypeHouselayoutYearBuilt.groupby(['City']).mean()

#Average House Prices Per house Type
RealEstatePriceDataByType = Real_Estate_PriceData_Groupedby_ProvinceCityHousetypeHouselayoutYearBuilt.groupby(['Type', 'City']).mean()

#Income Comparison Data
Canada2021_income_by_location= income_2021_bylocation_byage_byincomesource.groupby(['Location']).mean()
Canada2021_income_by_locationntype = income_2021_bylocation_byage_byincomesource.groupby(['Income Source Types','Location']).mean()

#Combined Data For Neural Network Analysis
LocationLogic = pd.concat([CensusLocationmerge, GlobalHappinessByCountry, RealEstatePriceDataByCity, Canada2021_income_by_location])

In [109]:
LocationLogic

,Total,Happiness Rank,Happiness Score,Economy,Family,Life Expectancy,Freedom,Government Trust,Generosity,Dystopia Residual,...,SqFt,Lot_Area,1 Year Median,1 Year Average,1 Year Aggregate,Percent of Total Income (1 Year),5 Year Median,5 Year Average,5 Year Aggregate,Percent of Total Income (5 Year)
Alberta,4.073838e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
British Columbia,5.067516e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Canada,3.975102e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Manitoba,1.395300e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New Brunswick,8.782292e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wood Buffalo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,17035.693182,21978.516364,358762.956364,16.853455,18736.647940,23436.611511,411005.327338,16.684173
Woodstock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,11108.875486,13811.714286,116957.953668,17.474517,10022.948718,12270.462633,90927.950178,16.148043
Yellowknife,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,16721.976923,19091.485075,84137.880597,17.056343,16088.529851,18935.618519,84245.666667,16.980000
Yorkton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,11249.460000,13246.564103,47803.582418,16.599267,9893.315985,12736.569892,46805.767025,16.212903
Yukon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,13181.152672,15840.210145,127399.757246,16.378261,11846.754647,14146.544803,101726.440860,16.209319

In [92]:
#Food
CA1

#660 Credit Score
CA4

#Rent
CA7

#Income Type Second Reference
CA10

,Quarter,2012Q3,2012Q4,2013Q1,2013Q2,2013Q3,2013Q4,2014Q1,2014Q2,2014Q3,...,2021Q1,2021Q2,2021Q3,2021Q4,2022Q1,2022Q2,2022Q3,2022Q4,2023Q1,2023Q2
0,Canada,8.0,7.9,7.9,7.5,7.8,8.8,8.0,7.2,7.3,...,4.0,3.8,4.2,4.3,4.1,4.2,4.7,4.9,5.1,5.0
1,Newfoundland,10.6,10.8,10.8,9.6,10.4,11.4,10.4,10.0,9.9,...,6.0,5.7,6.0,6.3,6.0,5.5,4.9,6.5,5.9,6.1
2,Prince Edward Island,10.4,8.0,9.6,8.6,10.5,9.5,11.6,10.0,8.8,...,4.0,3.7,5.2,5.2,4.6,4.8,5.1,4.4,6.0,6.0
3,Nova Scotia,10.4,10.4,10.4,9.9,10.6,11.5,11.0,10.1,10.1,...,5.7,4.5,5.1,5.0,5.4,4.9,5.1,6.0,6.0,6.1
4,New Brunswick,12.2,12.7,12.9,12.7,12.4,14.0,12.8,12.9,11.8,...,6.6,5.3,5.9,5.6,4.9,5.7,6.0,6.2,6.1,7.1
5,Qu�bec,6.5,6.0,6.0,5.9,6.1,6.9,6.3,5.4,5.6,...,3.1,3.0,3.4,3.4,3.1,3.2,3.8,4.0,4.0,4.0
6,Ontario,8.5,8.4,8.3,8.0,8.1,9.2,8.4,7.6,7.6,...,4.2,3.8,4.3,4.4,4.2,4.4,5.0,5.1,5.4,5.3
7,Manitoba,8.7,8.5,8.2,7.3,8.4,10.3,9.4,8.8,8.7,...,6.0,5.7,6.3,6.3,6.3,6.4,6.9,6.9,7.9,7.4
8,Saskatchewan,8.8,7.6,7.7,7.9,9.3,9.0,8.4,8.3,8.7,...,4.5,4.3,4.9,4.8,4.9,5.0,4.9,5.8,6.4,6.3
9,Alberta,8.6,8.5,8.8,8.5,8.9,10.0,8.8,8.4,8.5,...,5.1,4.6,4.9,5.4,5.2,5.3,5.7,5.6,6.2,6.0
10,British Columbia,7.8,7.9,7.6,7.4,7.6,8.0,7.6,6.9,6.8,...,3.7,3.7,4.1,4.1,3.9,3.9,4.4,4.4,4.5,4.4
11,Selected Metropolitan Areas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,St. John's,9.8,8.4,9.6,8.0,9.8,10.2,9.0,8.4,9.3,...,5.4,4.4,5.8,5.9,4.8,4.4,4.0,6.1,6.0,6.1
13,Charlottetown,9.6,7.0,7.8,8.6,9.9,8.0,8.2,10.0,8.8,...,4.0,3.3,4.0,4.8,3.9,4.5,4.8,4.0,4.1,4.2
14,Halifax,9.5,9.3,9.6,8.8,10.1,10.7,9.5,8.7,9.5,...,4.7,4.0,4.7,4.5,4.8,4.6,4.7,5.2,5.8,5.7
15,Moncton,11.5,11.2,11.5,11.0,11.2,12.2,11.1,12.1,11.2,...,5.1,5.5,6.2,4.9,4.4,5.2,5.1,5.7,4.9,5.7
16,Saint John,11.5,11.9,11.9,11.0,10.0,11.3,11.9,11.8,9.6,...,6.6,4.9,5.4,6.0,4.5,4.8,7.3,5.6,4.9,7.8
17,Saguenay,6.9,5.4,6.1,5.8,5.3,6.5,5.9,6.0,4.6,...,3.1,3.8,4.0,3.4,3.5,3.0,3.3,3.9,4.2,3.3
18,Qu�bec City,4.6,4.2,4.3,4.2,4.0,4.2,4.1,3.7,3.9,...,2.1,2.1,2.4,2.4,2.2,2.1,2.8,2.6,3.2,2.7
19,Sherbrooke,5.4,4.5,4.5,3.8,4.9,5.3,4.6,3.9,4.7,...,2.6,2.7,2.7,2.3,2.6,2.2,2.8,3.0,2.2,2.8
20,Trois-Rivi�res,5.5,5.9,4.5,5.2,4.7,5.4,6.7,5.7,4.5,...,3.0,2.7,4.0,4.0,4.0,3.2,3.6,3.3,2.5,4.0
21,Montr�al,6.7,6.6,6.0,6.1,6.5,7.6,6.7,5.6,6.0,...,3.0,2.9,3.5,3.4,3.2,3.3,4.1,4.3,4.1,4.4
22,Ottawa-Gatineau,6.8,6.9,7.4,6.5,6.0,8.1,6.5,6.3,5.9,...,3.4,3.1,3.6,3.6,3.5,3.5,3.9,4.5,4.5,4.7
23,Kingston,7.6,6.9,6.9,7.7,7.3,9.5,8.3,5.9,7.2,...,4.3,4.0,4.4,4.8,4.0,4.1,4.2,4.9,3.8,6.0
24,Peterborough,7.9,8.1,9.2,7.2,8.0,8.9,7.7,8.2,6.8,...,4.3,4.4,5.4,4.8,5.0,4.2,5.2,4.2,5.0,5.5
25,Oshawa,9.5,9.2,9.6,9.5,9.5,10.8,11.2,8.5,8.1,...,5.2,4.2,5.0,5.3,4.9,5.1,5.8,6.6,6.0,6.6
26,Toronto,8.0,7.8,7.8,7.5,7.5,8.2,7.7,7.1,7.2,...,3.6,3.3,3.7,3.8,3.6,3.8,4.6,4.9,4.8,4.7
27,Hamilton,9.1,9.1,8.4,8.5,8.2,9.3,9.7,7.3,7.8,...,3.5,3.7,4.6,4.5,4.3,4.7,4.5,4.7,5.4,5.2
28,St. Catharines-Niagara,10.1,10.8,9.2,9.4,10.0,11.9,9.4,9.3,7.9,...,5.2,6.0,6.0,5.9,6.1,6.5,6.0,6.2,6.9,6.7
29,Kitchener-Cambridge-Waterloo,8.4,8.3,8.5,8.1,8.5,9.3,7.5,7.3,7.7,...,4.1,3.6,4.6,4.4,3.6,3.8,4.9,4.4,4.6,5.3
30,Brantford,10.3,10.7,10.4,9.8,10.7,10.6,8.5,9.3,8.3,...,4.9,4.4,5.0,5.3,5.7,5.7,6.1,6.3,7.4,5.7
31,Guelph,8.5,8.1,7.5,6.5,7.0,8.6,6.8,6.7,6.0,...,3.7,3.5,3.6,3.3,3.9,3.5,4.2,4.3,4.2,4.7
32,London,8.4,8.8,8.3,9.6,8.0,10.6,9.1,7.9,8.3,...,4.3,3.9,4.7,5.0,4.6,4.5,5.0,5.2,5.9,5.7
33,Windsor,10.1,10.7,9.3,9.5,9.4,12.0,10.8,11.2,11.1,...,6.2,6.5,6.4,6.2,6.1,6.9,6.8,7.6,7.3,7.8
34,Barrie,10.1,9.5,7.9,9.9,10.2,11.0,10.1,9.3,8.6,...,5.5,5.4,5.5,6.1,5.7,4.5,6.0,6.9,6.0,6.2
35,Greater Sudbury,10.5,9.3,8.2,9.1,10.3,9.3,11.6,9.0,8.0,...,5.8,4.8,5.9,5.2,5.4,5.7,5.2,6.2,6.4,5.1
36,Thunder Bay,9.4,9.2,8.3,8.4,9.4,8.1,8.0,6.5,8.4,...,6.0,5.6,5.0,6.2,3.8,5.0,4.9,5.6,7.4,6.5
37,Winnipeg,8.7,8.3,8.2,6.9,8.0,10.3,9.8,8.9,8.6,...,5.8,5.3,5.9,6.1,6.1,6.2,6.4,6.6,7.5,7.2
38,Regina,7.1,7.3,7.9,7.5,9.7,8.6,8.1,7.6,8.0,...,5.4,4.0,5.0,4.4,5.0,5.0,4.9,4.8,6.9,6.5
39,Saskatoon,8.0,6.7,6.3,7.6,8.4,7.9,7.6,7.2,7.8,...,3.7,4.3,4.8,5.0,4.1,3.9,4.8,5.7,6.4,6.1
40,Calgary,7.7,8.1,8.6,8.2,8.2,9.1,7.9,8.0,7.6,...,4.6,4.0,4.2,4.9,4.5,4.9,5.0,5.5,5.6,5.4
41,Edmonton,8.3,8.1,8.4,8.4,9.2,10.0,9.6,8.5,8.7,...,5.0,4.7,5.1,5.9,5.6,5.4,6.0,6.1,7.1,6.7
42,Kelowna,8.5,7.1,8.9,7.6,8.4,7.8,8.7,8.3,7.1,...,3.3,3.5,3.5,3.8,4.5,3.8,3.9,4.1,4.1,4.8
43,Abbotsford-Mission,8.7,8.5,9.0,9.0,8.9,9.2,10.2,8.4,8.0,...,4.9,4.5,5.1,4.8,5.3,4.6,5.3,5.8,6.2,4.5
44,Vancouver,7.4,7.6,7.3,6.8,7.2,7.4,6.8,6.0,6.3,...,3.4,3.6,3.9,3.8,3.6,3.7,4.2,4.3,4.5,4.2
45,Victoria,7.2,6.7,5.9,6.8,6.0,6.5,6.4,6.4,6.5,...,3.0,2.7,3.4,3.0,3.2,2.9,3.7,3.3,3.4,3.4

In [81]:
#Date
#Canada_RealEstate_PricesbyDate = Real_Estate_PriceData_Groupedby_ProvinceCityHousetypeHouselayoutYearBuilt.groupby('Year_Built').mean()
#household_liability_indexed_by_date.index = pd.to_datetime(household_liability_indexed_by_date.index).year
#household_liability_indexed_by_date = household_liability_indexed_by_date.groupby(['Period']).mean()
#Income_Per_Capita_indexed_by_date
#Canada_CPI_Indexed_By_Date
#Canada_Happiness_20152022 = Global_Happiness_20152022.xs('Canada', level='Country')
#Canada_Happiness_ByYear = Canada_Happiness_20152022.groupby('Year').mean()
#Global_Happiness_ByYear = Global_Happiness_20152022.groupby('Year').mean()
#variable2 = Canada_Household_Wealth.xs('Total All Households', level='Profile')
#CanadaHouseholdWealthAnnualAverages = variable2.groupby('Years').mean()
#CensusDate1 = CensusLogic1.groupby(['Year']).mean()
#CensusDateLogic2 = CensusLogic2.groupby(['Year']).mean()
#DateLogic = pd.concat([CensusDateLogic2, CensusDate1, CanadaHouseholdWealthAnnualAverages, Canada_Happiness_ByYear, Global_Happiness_ByYear, Canada_CPI_Indexed_By_Date, Income_Per_Capita_indexed_by_date, household_liability_indexed_by_date, Canada_RealEstate_PricesbyDate])

#DateX = DateLogic.index.fillna('')
#Datey = DateLogic[columns_to_convert].fillna('')

# Split the data into training and testing sets
#DateX_train, DateX_test, Datey_train, Datey_test = train_test_split(DateX, Datey, test_size=0.2, random_state=15)

# Standardize the input data
#Datonator = StandardScaler()
#DateX_train_scaled = Datonator.fit_transform(DateX_train.values.reshape(-1, 1))
#DateX_test_scaled = Datonator.transform(DateX_test.values.reshape(-1, 1))

# Build and train the KNeighborsRegressor model
#Dateknn = KNeighborsRegressor(n_neighbors=5)
#Dateknn.fit(DateX_train_scaled, Datey_train)


#Model Evaluation
#Datey_pred = Dateknn.predict(DateX_test_scaled)
#Datey_test = pd.to_numeric(Datey_test, errors='coerce')
#datemae = mean_absolute_error(Datey_test, Datey_pred)
#print(f'Date Machine Mean Absolute Error: {datemae}')
#dater2 = r2_score(Datey_test, agey_pred)
#print(f'Date Machine R-squared: {dater2}')